In [1]:
import pandas as pd

In [3]:
Sales = pd.read_csv("sales_data_large_project.csv")
Sales.head()

   order_id  order_date     product     category  quantity  price region
0      1001  2023-01-01  Headphones  Accessories         4  12000  North
1      1002  2023-01-02  Smartwatch  Accessories         1  12000   West
2      1003  2023-01-03      Tablet  Accessories         3  55000  North
3      1004  2023-01-04  Smartwatch  Accessories         5  12000   West
4      1005  2023-01-05  Smartwatch  Accessories         3  12000   East

In [4]:
Sales.shape

(1000, 7)

In [11]:
Sales.describe()

          order_id     quantity         price
count  1000.000000  1000.000000   1000.000000
mean   1500.500000     3.045000  20205.000000
std     288.819436     1.424431  19273.672443
min    1001.000000     1.000000   2000.000000
25%    1250.750000     2.000000   5000.000000
50%    1500.500000     3.000000  12000.000000
75%    1750.250000     4.000000  25000.000000
max    2000.000000     5.000000  55000.000000

In [12]:
#checking Duplicates 
Sales.duplicated().sum()

np.int64(0)

In [13]:
#Now we have to Drop the duplicates if the exists
Sales = Sales.drop_duplicates()

In [14]:
Sales

     order_id  order_date     product     category  quantity  price region
0        1001  2023-01-01  Headphones  Accessories         4  12000  North
1        1002  2023-01-02  Smartwatch  Accessories         1  12000   West
2        1003  2023-01-03      Tablet  Accessories         3  55000  North
3        1004  2023-01-04  Smartwatch  Accessories         5  12000   West
4        1005  2023-01-05  Smartwatch  Accessories         3  12000   East
..        ...         ...         ...          ...       ...    ...    ...
995      1996  2025-09-22      Laptop  Accessories         3   2000  South
996      1997  2025-09-23      Mobile  Accessories         4   2000   West
997      1998  2025-09-24      Mobile  Electronics         1   5000  North
998      1999  2025-09-25  Headphones  Accessories         3  55000   West
999      2000  2025-09-26      Tablet  Accessories         2   2000  South

[1000 rows x 7 columns]

In [15]:
#checking null values in Data Farame Sales
Sales.isnull().sum()

order_id      0
order_date    0
product       0
category      0
quantity      0
price         0
region        0
dtype: int64

In [21]:
Sales.dtypes

order_id               int64
order_date    datetime64[ns]
product               object
category              object
quantity               int64
price                  int64
region                object
dtype: object

In [20]:
Sales['order_date'] = pd.to_datetime(Sales['order_date'])

Coverting the Column names in  title format

In [24]:
Sales.columns = Sales.columns.str.title()

In [26]:
Sales.head()

   Order_Id Order_Date     Product     Category  Quantity  Price Region
0      1001 2023-01-01  Headphones  Accessories         4  12000  North
1      1002 2023-01-02  Smartwatch  Accessories         1  12000   West
2      1003 2023-01-03      Tablet  Accessories         3  55000  North
3      1004 2023-01-04  Smartwatch  Accessories         5  12000   West
4      1005 2023-01-05  Smartwatch  Accessories         3  12000   East

Creating a New column Revenue

In [27]:
Sales['Revenue'] = Sales['Quantity'] * Sales['Price']

In [28]:
Sales.head()

,Order_Id,Order_Date,Product,Category,Quantity,Price,Region,Revenue
0,1001,2023-01-01,Headphones,Accessories,4,12000,North,48000
1,1002,2023-01-02,Smartwatch,Accessories,1,12000,West,12000
2,1003,2023-01-03,Tablet,Accessories,3,55000,North,165000
3,1004,2023-01-04,Smartwatch,Accessories,5,12000,West,60000
4,1005,2023-01-05,Smartwatch,Accessories,3,12000,East,36000

In [30]:
Sales['Revenue'].dtype

dtype('int64')

Understand the Size of Business

In [33]:
#Cotunt number of rows that means wec an Know the number of orders (business Size)
Sales.shape[0]

1000

Total business value?

In [39]:
print(Sales.Revenue.sum())

59020000

Average Order Value (AOV)

In [41]:
print(Sales['Revenue'].mean())

59020.0

Product-wise Revenue

In [42]:
Sales.groupby('Product')['Revenue'].sum().sort_values(ascending = False)

Product
Smartwatch    14104000
Mobile        11955000
Laptop        11429000
Headphones    11290000
Tablet        10242000
Name: Revenue, dtype: int64

Region-wise Revenue

In [43]:
Sales.groupby('Region')['Revenue'].sum().sort_values(ascending = False)

Region
East     15501000
South    15298000
North    14978000
West     13243000
Name: Revenue, dtype: int64

Monthly Revenue Trend (Very Important)

In [46]:
Sales['Month'] = Sales['Order_Date'].dt.to_period('M')

In [47]:
Sales

,Order_Id,Order_Date,Product,Category,Quantity,Price,Region,Revenue,Month
0,1001,2023-01-01,Headphones,Accessories,4,12000,North,48000,2023-01
1,1002,2023-01-02,Smartwatch,Accessories,1,12000,West,12000,2023-01
2,1003,2023-01-03,Tablet,Accessories,3,55000,North,165000,2023-01
3,1004,2023-01-04,Smartwatch,Accessories,5,12000,West,60000,2023-01
4,1005,2023-01-05,Smartwatch,Accessories,3,12000,East,36000,2023-01
...,...,...,...,...,...,...,...,...,...
995,1996,2025-09-22,Laptop,Accessories,3,2000,South,6000,2025-09
996,1997,2025-09-23,Mobile,Accessories,4,2000,West,8000,2025-09
997,1998,2025-09-24,Mobile,Electronics,1,5000,North,5000,2025-09
998,1999,2025-09-25,Headphones,Accessories,3,55000,West,165000,2025-09
999,2000,2025-09-26,Tablet,Accessories,2,2000,South,4000,2025-09

In [48]:
Sales.groupby('Month')['Revenue'].sum()

Month
2023-01    1683000
2023-02    1896000
2023-03    2142000
2023-04    1641000
2023-05    1588000
2023-06    1649000
2023-07    1587000
2023-08    1563000
2023-09    1447000
2023-10    2740000
2023-11    1106000
2023-12    1843000
2024-01    1537000
2024-02    1572000
2024-03    2750000
2024-04    2110000
2024-05    2128000
2024-06    1379000
2024-07    2345000
2024-08    2048000
2024-09    1871000
2024-10    1229000
2024-11    1684000
2024-12    1759000
2025-01    2687000
2025-02    1202000
2025-03    2447000
2025-04    1577000
2025-05    1978000
2025-06    1565000
2025-07    1451000
2025-08    1424000
2025-09    1392000
Freq: M, Name: Revenue, dtype: int64

In [50]:
Sales.to_csv("Sales_DA_Clean" , index = False)

In [51]:
Sales

,Order_Id,Order_Date,Product,Category,Quantity,Price,Region,Revenue,Month
0,1001,2023-01-01,Headphones,Accessories,4,12000,North,48000,2023-01
1,1002,2023-01-02,Smartwatch,Accessories,1,12000,West,12000,2023-01
2,1003,2023-01-03,Tablet,Accessories,3,55000,North,165000,2023-01
3,1004,2023-01-04,Smartwatch,Accessories,5,12000,West,60000,2023-01
4,1005,2023-01-05,Smartwatch,Accessories,3,12000,East,36000,2023-01
...,...,...,...,...,...,...,...,...,...
995,1996,2025-09-22,Laptop,Accessories,3,2000,South,6000,2025-09
996,1997,2025-09-23,Mobile,Accessories,4,2000,West,8000,2025-09
997,1998,2025-09-24,Mobile,Electronics,1,5000,North,5000,2025-09
998,1999,2025-09-25,Headphones,Accessories,3,55000,West,165000,2025-09
999,2000,2025-09-26,Tablet,Accessories,2,2000,South,4000,2025-09

In [54]:
Sales = Sales.drop(columns = ['Month'])

In [55]:
Sales

,Order_Id,Order_Date,Product,Category,Quantity,Price,Region,Revenue
0,1001,2023-01-01,Headphones,Accessories,4,12000,North,48000
1,1002,2023-01-02,Smartwatch,Accessories,1,12000,West,12000
2,1003,2023-01-03,Tablet,Accessories,3,55000,North,165000
3,1004,2023-01-04,Smartwatch,Accessories,5,12000,West,60000
4,1005,2023-01-05,Smartwatch,Accessories,3,12000,East,36000
...,...,...,...,...,...,...,...,...
995,1996,2025-09-22,Laptop,Accessories,3,2000,South,6000
996,1997,2025-09-23,Mobile,Accessories,4,2000,West,8000
997,1998,2025-09-24,Mobile,Electronics,1,5000,North,5000
998,1999,2025-09-25,Headphones,Accessories,3,55000,West,165000
999,2000,2025-09-26,Tablet,Accessories,2,2000,South,4000

In [56]:
Sales.to_csv('Sales_DA_Cleaned.csv', index = False)